version: "3"
services:
  riemann:
    network_mode: "host"
    image: riemannio/riemann:latest
    ports:
      - "127.0.0.1:5555:5555"
      - "127.0.0.1:5556:5556"
    volumes:
      - ./riemann.config:/etc/riemann.config
